services:
  backend:
    image: arioum/docker-actions-demo-backend:${TAG}
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    image: arioum/docker-actions-demo-frontend:${TAG}
    ports:
      - "3000:80"
    restart: unless-stopped
