services:
  backend:
    build:
      context: ./backend
    image: arioum/docker-actions-demo-backend:${TAG}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    image: arioum/docker-actions-demo-frontend:${TAG}
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    restart: unless-stopped
